#+title: google-api.el
#+author: Naoya Yamashita

[[https://github.com/conao3/google-api.el][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/google-api.el.png]]

[[https://github.com/conao3/google-api.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/google-api.el.svg?style=flat-square]]
[[https://github.com/conao3/google-api.el/releases][https://img.shields.io/github/tag/conao3/google-api.el.svg?style=flat-square]]
[[https://github.com/conao3/google-api.el/actions][https://github.com/conao3/google-api.el/workflows/Main%20workflow/badge.svg]]

Google API client library for Emacs.

* Overview

google-api.el provides a foundation for interacting with Google APIs from Emacs. It handles OAuth2 authentication and offers a clean interface for making API requests.

** Features

- OAuth2 authentication support via =oauth2-request=
- Async/await pattern for non-blocking API calls
- Extensible class-based design using EIEIO
- Google Calendar API submodule included

* Requirements

- Emacs 26.1 or later
- [[https://github.com/pkulev/oauth2-request][oauth2-request]] (0.14+)
- [[https://github.com/chuntaro/emacs-async-await][async-await]] (1.1+)

* Installation

** Using leaf.el

#+begin_src emacs-lisp
(leaf google-api :ensure t)
#+end_src

** Using use-package

#+begin_src emacs-lisp
(use-package google-api
  :ensure t)
#+end_src

** Manual Installation

Clone this repository and add it to your =load-path=:

#+begin_src emacs-lisp
(add-to-list 'load-path "/path/to/google-api.el")
(require 'google-api)
#+end_src

* Usage

The package provides a base class =google-api-token= that can be extended for specific Google APIs. The included =google-calendar-api= module demonstrates this pattern:

#+begin_src emacs-lisp
(require 'google-calendar-api)

;; Create a token instance with your OAuth2 credentials
(setq my-token (google-calendar-api-token
                :client-id "your-client-id"
                :client-secret "your-client-secret"))
#+end_src

* Contributing

Contributions are welcome. Please feel free to submit issues and pull requests.

** Development Setup

Install [[https://github.com/conao3/keg][keg]] for testing:

#+begin_src shell
git clone https://github.com/conao3/keg ~/.keg
export PATH="$HOME/.keg/bin:$PATH"
#+end_src

** Workflow

#+begin_src shell
git checkout -b your-feature-branch
# Make your changes
make test
git commit -am "Description of changes"
#+end_src

* License

GPL-3.0. See [[https://github.com/conao3/google-api.el/blob/master/LICENSE][LICENSE]] for details.

Copyright (C) Naoya Yamashita

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
